
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      PORT: 3006
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      ENABLE_CACHING: ${ENABLE_CACHING}
    volumes:
      - .:/app
    command: ["npm", "start"]

  frontend:
    build:
      context: ./elaniin_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./elaniin_front:/app
    command: ["npm", "run", "dev"]


